CREATE TABLE Data_Annotated_Annovar_Data (
    Sl_No INT AUTO_INCREMENT PRIMARY KEY,               -- Serial Number
    NCB_SRA_ID VARCHAR(50),
    Chr VARCHAR(5),
    Start INT,
    End INT,
    Ref VARCHAR(10),
    Alt VARCHAR(10),
    Func_refGene VARCHAR(100),
    ExonicFunc_refGene VARCHAR(100),
    AAChange_refGene TEXT,
    CADD VARCHAR(10),
    CADD_Phred VARCHAR(100),
    Polyphen2_HDIV_score VARCHAR(100),
    Polyphen2_HDIV_rankscore VARCHAR(100),
    Polyphen2_HDIV_pred VARCHAR(10),
    Polyphen2_HVAR_score VARCHAR(100),
    Polyphen2_HVAR_rankscore VARCHAR(100),
    Polyphen2_HVAR_pred VARCHAR(10),
    SIFT_pred VARCHAR(10),
    MutationTaster_score VARCHAR(100),
    MutationTaster_converted_rankscore VARCHAR(100),
    MutationTaster_pred VARCHAR(10),
    MutationAssessor_score VARCHAR(100),
    MutationAssessor_rankscore VARCHAR(100),
    MutationAssessor_pred VARCHAR(10),
    SIFT_score VARCHAR(100),
    SIFT_converted_rankscore VARCHAR(100),
    SIFT_pred VARCHAR(10),
    SIFT4G_score VARCHAR(100),
    SIFT4G_converted_rankscore VARCHAR(100),
    SIFT4G_pred VARCHAR(10),
    CLNSIG VARCHAR(100),
    AF VARCHAR(100),
    AF_popmax VARCHAR(100)
);
